### ISSUE TITLE
[Info] main/jsonem: Reading config: stdin:

### ISSUE THREAD

**Issue by norman8335** [zw963/asuswrt-merlin-v2ray#1]
deploy status 
`root@Dostyle:/mnt/f/ASUS/asuswrt-merlin-v2ray-4.43.0# ./deploy_router admin@192.168.50.1
admin@192.168.50.1's password:
admin@192.168.50.1's password:
v2ray.json                                                                            100% 3284   292.3KB/s   00:00
admin@192.168.50.1's password:
apply_iptables_rule.sh                                                                100% 6784   688.9KB/s   00:00
admin@192.168.50.1's password:
clean_iptables_rule.sh                                                                100% 1314   210.7KB/s   00:00
admin@192.168.50.1's password:
enable_swap.sh                                                                        100%  482    31.2KB/s   00:00
admin@192.168.50.1's password:
update_geosite.sh                                                                     100%  803    58.5KB/s   00:00
admin@192.168.50.1's password:
update_big_geosite.sh                                                                 100%  813    72.0KB/s   00:00
admin@192.168.50.1's password:
restart_dnsmasq.sh                                                                    100%  156     7.5KB/s   00:00
admin@192.168.50.1's password:
toggle_proxy.sh                                                                       100% 5814   567.1KB/s   00:00
admin@192.168.50.1's password:
patch_router                                                                          100%  269    18.3KB/s   00:00
admin@192.168.50.1's password:
check_google_use_proxy.sh                                                             100%  113     5.8KB/s   00:00
admin@192.168.50.1's password:
check_google_use_socks5.sh                                                            100%  146    10.3KB/s   00:00
admin@192.168.50.1's password:
debug_v2ray.sh                                                                        100%  973    58.8KB/s   00:00
Copy predownloaded binary to router ...
admin@192.168.50.1's password:
admin@192.168.50.1's password:
v2ray-linux-arm32-v5.zip                                                              100%   13MB 345.0KB/s   00:37
admin@192.168.50.1's password:
admin@192.168.50.1's password:
***********************************************************
Remote deploy scripts is started !!
***********************************************************
opkg version 1bf042dd06751b693a8544d2317e5b969d666b69 (2021-06-13)
Archive:  v2ray-linux-arm32-v5.zip
  inflating: vpoint_socks_vmess.json
  inflating: v2ctl
  inflating: config.json
  inflating: vpoint_vmess_freedom.json
  inflating: geoip-only-cn-private.dat
  inflating: v2ray
  inflating: geosite.dat
  inflating: systemd/system/v2ray@.service
  inflating: systemd/system/v2ray.service
  inflating: geoip.dat
V2Ray 4.43.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.1 linux/arm)
A unified platform for anti-censorship.
 Checking v2ray...              dead.
v2ray was installed.
 => Disabling proxy ...
 Checking v2ray...              dead.
Cleaning iptables rule ... done.
Restart dnsmasq ... done.
 => Proxy is disabled.
--------------
 => Enabling proxy ...
Apply TProxy config ...
Applying iptables rule ...can not find out v2ray port setting in /opt/etc/v2ray.json
 Starting v2ray...              done.
Restart dnsmasq ... done.
 => Proxy is enabled.
Congratulations, Deploy succssful!`

v2ray satrt error `admin@RT-AC1900P-A948:/tmp/home/root# v2ray
V2Ray 4.43.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.17.1 linux/arm)
A unified platform for anti-censorship.
2021/10/31 00:11:54 Using config from STDIN
2021/10/31 00:11:54 [Info] main/jsonem: Reading config: stdin:
` 
please help

**Comment by zw963** [comment]
You should copy a valid v2ray client config file into host router/opt/etc/v2ray.json, or copy to routers /opt/etc/ directly.

if you don't know how to write it, you need deploy server first, it will create a client config for you.
