### ISSUE TITLE
deploy_start.sh line 174 scp cmd needs -O option.

### ISSUE THREAD

**Issue by PeiyuanQi** [zw963/asuswrt-merlin-v2ray#10]
similar issue is https://forum.openwrt.org/t/ash-usr-libexec-sftp-server-not-found-when-using-scp/125772/3

add -O might not be the correct solution considering in future versions -O might be removed.

**Comment by zw963** [comment]
> add -O might not be the correct solution considering in future versions -O might be removed.

Thanks for mention this, because the `copy` command is used for both use scp copy file into router(AC5300) and remote VPS, so, i add `-O` option for support the older router, maybe i can figure out a way to fix this.

**Comment by PeiyuanQi** [comment]
make sense feel free to close.

also i find deploy server side with d2ray docker image is faster.
