### ISSUE TITLE
v24.11.21 版本部署后路由器故障

### ISSUE THREAD

**Issue by peilin-liu** [zw963/asuswrt-merlin-v2ray#13]
您好，我使用v24.11.21部署成功后，出现路由器无法连接，家庭设备也无法上网问题。ssh 端口也连不上了，只能拔掉u 盘，重新启动才能恢复正常网络功能。
是在路由器上执行如下指令来部署的
router_arch=linux-arm64-v8a bash ./deploy_router localhost. 
请问这是因为我的部署方式不对引起的吗？

**Comment by zw963** [comment]
好吧, 是我写的不够好, 你得先在服务器端部署好 Xray 脚本, 然后(自动拷贝生成的客户端脚本到本地), 再运行另一个脚本部署到路由器.

1. router_arch=linux-arm64-v8a ./deploy_server root@你的服务器IP
    这一步如果没报错, 继续下一步.

3. ./deploy_router root@你的路由器IP

**Comment by peilin-liu** [comment]
在部署路由器之前，我已经使用 router_arch=linux-arm64-v8a ./deploy_server root@你的服务器IP 部署好了服务器。不过后续部署路由器的时候，我是把完整目录copy 到路由器执行 router_arch=linux-arm64-v8a bash ./deploy_router localhost 来部署的。因我我在我的mac 远程上部署路由器一直失败。

**Comment by zw963** [comment]
>  router_arch=linux-arm64-v8a ./deploy_server root@你的服务器IP

这个成功了, 对吗? 典型的, 服务器上应该能看到 xray 服务已经被启动成功了. systemctl status xray

> 我是把完整目录copy 到路由器执行 router_arch=linux-arm64-v8a bash ./deploy_router localhost 

这种方式我没试过, 我是本机运行:  router_arch=linux-arm64-v8a bash ./deploy_router root@192.168.50.1 (假设路由器地址为 192.168.50.1)

我这个脚本主要是自用, 没有很好的错误处理, 如果确实有问题, 请提供部署时显示的完整的日志(隐藏掉密码等信息), 也一并贴上来.

**Comment by peilin-liu** [comment]
> > router_arch=linux-arm64-v8a ./deploy_server root@你的服务器IP
> 
> 这个成功了, 对吗? 典型的, 服务器上应该能看到 xray 服务已经被启动成功了. systemctl status xray
> 
> > 我是把完整目录copy 到路由器执行 router_arch=linux-arm64-v8a bash ./deploy_router localhost
> 
> 这种方式我没试过, 我是本机运行: router_arch=linux-arm64-v8a bash ./deploy_router root@192.168.50.1 (假设路由器地址为 192.168.50.1)
> 
> 我这个脚本主要是自用, 没有很好的错误处理, 如果确实有问题, 请提供部署时显示的完整的日志(隐藏掉密码等信息), 也一并贴上来.
