### ISSUE TITLE
local file router/opt/etc/restart_dnsmasq is missing ...

### ISSUE THREAD

**Issue by BoxingP** [zw963/asuswrt-merlin-v2ray#3]
macOS 10.14.4
iterm2 (zsh)
asus merlin 384.15

use
`./deploy_v2ray_to_router root@192.168.50.1`
meets this error:

> Disabling proxy ...
> Cleaning iptables rule ...
> Done clean iptables rule.
> dnsmasq: syntax check OK.
> Proxy is disabled.
> v2ray.json                                    100% 7358   610.8KB/s   00:00
> apply_iptables_rule.sh                        100% 1940   182.1KB/s   00:00
> clean_iptables_rule.sh                        100% 1072    99.5KB/s   00:00
> toggle_proxy.sh                               100% 1522   140.6KB/s   00:00
> enable_swap.sh                                100%  482    45.2KB/s   00:00
> patch_router                                  100%  214    21.6KB/s   00:00
> local file router/opt/etc/restart_dnsmasq is missing ...

I copied this file from 
https://github.com/zw963/asuswrt-merlin-transparent-proxy
and then looks good
But looks restart_dnsmasq.sh isn't needed in the after progress?

**Comment by zw963** [comment]
sorry, it is bug, restart_dnsmasq.sh is necessary, was fixed in recent version.
