### ISSUE TITLE
./deploy_router: line 26: copy: command not found

### ISSUE THREAD

**Issue by myfreax** [zw963/asuswrt-merlin-v2ray#4]
Thank your work. The deploy_router script throw error `copy command not found` when try install v2ray on ac68u router. I think `copy` is custom shell function.  

The `copy` function, it possible  from script `https://gitee.com/zw963/deployment_bash/raw/v0.7.2/deploy_start.sh`. But the link return 404

**Comment by zw963** [comment]
是的， gitee 服务用了一阵子，然后莫名其妙的将我这个纯技术的 repo deploy_start.sh 标记为违规，然后就再也删除不用了。

你再试一下。

**Comment by myfreax** [comment]
Thank，It work well.
