### ISSUE TITLE
Is AC68U strong enough to use this script?

### ISSUE THREAD

**Issue by zjmonk** [zw963/asuswrt-merlin-v2ray#8]
Thank you for share this amazing script!

I have a AC68U, I note that you have another repo asuswrt-merlin-transparent-proxy, it methioned that this script needs a **morden** router, I wonder if AC68u is modern enough, or I should just try the old repo?

This old repo also support v2ray, what's difference? Thanks!

**Comment by zw963** [comment]
old router should use https://github.com/zw963/asuswrt-merlin-transparent-proxy/blob/master/ss%2Bdnsmasq%2Bdnscrypt

though, i don't know if it still work because i never use it since two years ago.
